// <auto-generated />
using System;
using FirstApiProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstApiProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922013400_dataseeding")]
    partial class dataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstApiProject.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            GradeLevel = 1,
                            Name = "Room 101 - Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            GradeLevel = 2,
                            Name = "Room 202 - Beta"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 35,
                            GradeLevel = 3,
                            Name = "Room 303 - Gamma"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 20,
                            GradeLevel = 1,
                            Name = "Lab A - Computer Center"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 22,
                            GradeLevel = 2,
                            Name = "Lab B - Science Hall"
                        });
                });

            modelBuilder.Entity("FirstApiProject.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Software Engineering and Architecture",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pure and Applied Mathematics",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classical and Quantum Mechanics",
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Big Data, Analytics, and AI Systems",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Business Technology Infrastructure",
                            Name = "Information Systems"
                        });
                });

            modelBuilder.Entity("FirstApiProject.Models.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 92.50m,
                            Id = 1
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 88.00m,
                            Id = 2
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            EnrollmentDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95.00m,
                            Id = 3
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 4,
                            EnrollmentDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 89.75m,
                            Id = 4
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 3,
                            EnrollmentDate = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 91.00m,
                            Id = 5
                        });
                });

            modelBuilder.Entity("FirstApiProject.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassRoomId = 1,
                            DateOfBirth = new DateTime(2005, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ahmed.ali@example.com",
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            PhoneNumber = "01023456789"
                        },
                        new
                        {
                            Id = 2,
                            ClassRoomId = 2,
                            DateOfBirth = new DateTime(2006, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "sara.k@example.com",
                            FirstName = "Sara",
                            LastName = "Kamal",
                            PhoneNumber = "01276543210"
                        },
                        new
                        {
                            Id = 3,
                            ClassRoomId = 1,
                            DateOfBirth = new DateTime(2005, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "omar.h@example.com",
                            FirstName = "Omar",
                            LastName = "Hassan",
                            PhoneNumber = "01145678901"
                        },
                        new
                        {
                            Id = 4,
                            ClassRoomId = 3,
                            DateOfBirth = new DateTime(2004, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "yasmine.m@example.com",
                            FirstName = "Yasmine",
                            LastName = "Moustafa",
                            PhoneNumber = "01598765432"
                        },
                        new
                        {
                            Id = 5,
                            ClassRoomId = 2,
                            DateOfBirth = new DateTime(2006, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mostafa.m@example.com",
                            FirstName = "Mostafa",
                            LastName = "Mahmoud",
                            PhoneNumber = "01011223344"
                        });
                });

            modelBuilder.Entity("FirstApiProject.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxGrade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Building backend systems with EF Core",
                            MaxGrade = 100,
                            Name = "Web Development API",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Limits, derivatives, and integrations",
                            MaxGrade = 100,
                            Name = "Calculus I",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Introduction to atomic structures",
                            MaxGrade = 100,
                            Name = "Quantum Physics",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Supervised and unsupervised learning models",
                            MaxGrade = 100,
                            Name = "Machine Learning",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "SQL, normalization, and indexing patterns",
                            MaxGrade = 100,
                            Name = "Database Management Systems",
                            TeacherId = 5
                        });
                });

            modelBuilder.Entity("FirstApiProject.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            EmailAddress = "j.doe@school.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "+123456789",
                            Salary = 5500.00m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            EmailAddress = "j.smith@school.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "+987654321",
                            Salary = 6000.00m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            EmailAddress = "r.johnson@school.com",
                            FirstName = "Robert",
                            LastName = "Johnson",
                            PhoneNumber = "+111222333",
                            Salary = 5800.00m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            EmailAddress = "e.davis@school.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            PhoneNumber = "+444555666",
                            Salary = 6200.00m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            EmailAddress = "m.brown@school.com",
                            FirstName = "Michael",
                            LastName = "Brown",
                            PhoneNumber = "+777888999",
                            Salary = 5400.00m
                        });
                });

            modelBuilder.Entity("FirstApiProject.Models.Enrollment", b =>
                {
                    b.HasOne("FirstApiProject.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstApiProject.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FirstApiProject.Models.Student", b =>
                {
                    b.HasOne("FirstApiProject.Models.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("FirstApiProject.Models.Subject", b =>
                {
                    b.HasOne("FirstApiProject.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("FirstApiProject.Models.Teacher", b =>
                {
                    b.HasOne("FirstApiProject.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FirstApiProject.Models.Classroom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("FirstApiProject.Models.Department", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("FirstApiProject.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("FirstApiProject.Models.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("FirstApiProject.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
